name: Bug report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug. Please be specific.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug and what you expected instead.
      placeholder: When I tap Maps, nothing opens even though Organic Maps is installed.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open Page
        2. Tap "Maps"
        3. ...
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: Pixel 6a
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: Android 14 (API 34)
    validations:
      required: true
  - type: input
    id: page-version
    attributes:
      label: Page version
      placeholder: 0.1.0
    validations:
      required: false
